[package]
name = "pci"
version = "0.1.0"

[lib]
name = "pci"
path = "lib.rs"

[dependencies]
kernel = { path = "../../kernel" }

[dependencies.intrusive-collections]
version = "0.7.4"
default-features = false
features = [ "nightly", "alloc" ]
