version: 2
jobs:
  build:
    docker:
      - image: "fedora:30"
    steps:
      - checkout
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: source $HOME/.profile
      - run: ./scripts/install-toolchain
      - run: HOME=$HOME/.cargo/bin:$HOME make V=1 kernel.elf
