[package]
name = "kernel"
version = "0.1.0"

[lib]
path = "lib.rs"

[dependencies]
bitflags = { version = "0.9" }
intrusive-collections = { version = "0.7.4", default-features = false, features = [ "nightly", "alloc" ]}
rlibc = { version = "1.0.0" }
xmas-elf = { version = "0.6" }
