[package]
name = "kernel"
version = "0.1.0"

[lib]
path = "lib.rs"

[dependencies.intrusive-collections]
version = "0.6.4"
default-features = false
features = [ "nightly", "alloc" ]

[dependencies.rlibc]
version = "1.0.0"

[dependencies.xmas-elf]
version = "0.5"
